server:
  port: 8081

spring:
  application:
    name: user-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888

auth:
  token:
    secretKey: ${SECRET-KEY}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,busrefresh



