server:
  port: 8082

spring:
  application:
    name: ticket-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888
  elasticsearch:
    uris: localhost:9200

auth:
  token:
    secretKey: ${SECRET-KEY}

